#pragma once

// Enumとその文字列について展開するマクロ
#define FWK_JSON_ENUM_VALUE(a_value) { a_value, #a_value }

// NLOHMANN_JSON_SERIALIZE_ENUMを少ない記述量で呼び出すための補助マクロ
#define FWK_JSON_SERIALIZE_ENUM(a_enumType, ...) \
NLOHMANN_JSON_SERIALIZE_ENUM   (a_enumType,      \
{												 \
	__VA_ARGS__									 \
})

// 塗りつぶしモード
FWK_JSON_SERIALIZE_ENUM(D3D12_FILL_MODE,
	FWK_JSON_ENUM_VALUE(D3D12_FILL_MODE_WIREFRAME),
	FWK_JSON_ENUM_VALUE(D3D12_FILL_MODE_SOLID)
)

// カリングモード
FWK_JSON_SERIALIZE_ENUM(D3D12_CULL_MODE,
	FWK_JSON_ENUM_VALUE(D3D12_CULL_MODE_NONE),
	FWK_JSON_ENUM_VALUE(D3D12_CULL_MODE_FRONT),
	FWK_JSON_ENUM_VALUE(D3D12_CULL_MODE_BACK)
)

// ブレンド係数
FWK_JSON_SERIALIZE_ENUM(D3D12_BLEND,
	FWK_JSON_ENUM_VALUE(D3D12_BLEND_ZERO),
	FWK_JSON_ENUM_VALUE(D3D12_BLEND_ONE),
	FWK_JSON_ENUM_VALUE(D3D12_BLEND_SRC_COLOR),
	FWK_JSON_ENUM_VALUE(D3D12_BLEND_INV_SRC_COLOR),
	FWK_JSON_ENUM_VALUE(D3D12_BLEND_SRC_ALPHA),
	FWK_JSON_ENUM_VALUE(D3D12_BLEND_INV_SRC_ALPHA),
	FWK_JSON_ENUM_VALUE(D3D12_BLEND_DEST_ALPHA),
	FWK_JSON_ENUM_VALUE(D3D12_BLEND_INV_DEST_ALPHA),
	FWK_JSON_ENUM_VALUE(D3D12_BLEND_DEST_COLOR),
	FWK_JSON_ENUM_VALUE(D3D12_BLEND_INV_DEST_COLOR)
)

// ブレンド演算
FWK_JSON_SERIALIZE_ENUM(D3D12_BLEND_OP,
	FWK_JSON_ENUM_VALUE(D3D12_BLEND_OP_ADD),
	FWK_JSON_ENUM_VALUE(D3D12_BLEND_OP_SUBTRACT),
	FWK_JSON_ENUM_VALUE(D3D12_BLEND_OP_REV_SUBTRACT),
	FWK_JSON_ENUM_VALUE(D3D12_BLEND_OP_MIN),
	FWK_JSON_ENUM_VALUE(D3D12_BLEND_OP_MAX)
)

// 深度書き込みマスク
FWK_JSON_SERIALIZE_ENUM(D3D12_DEPTH_WRITE_MASK,
	FWK_JSON_ENUM_VALUE(D3D12_DEPTH_WRITE_MASK_ZERO),
	FWK_JSON_ENUM_VALUE(D3D12_DEPTH_WRITE_MASK_ALL)
)

// 比較関数
FWK_JSON_SERIALIZE_ENUM(D3D12_COMPARISON_FUNC,
	FWK_JSON_ENUM_VALUE(D3D12_COMPARISON_FUNC_NEVER),
	FWK_JSON_ENUM_VALUE(D3D12_COMPARISON_FUNC_LESS),
	FWK_JSON_ENUM_VALUE(D3D12_COMPARISON_FUNC_EQUAL),
	FWK_JSON_ENUM_VALUE(D3D12_COMPARISON_FUNC_LESS_EQUAL),
	FWK_JSON_ENUM_VALUE(D3D12_COMPARISON_FUNC_GREATER),
	FWK_JSON_ENUM_VALUE(D3D12_COMPARISON_FUNC_NOT_EQUAL),
	FWK_JSON_ENUM_VALUE(D3D12_COMPARISON_FUNC_GREATER_EQUAL),
	FWK_JSON_ENUM_VALUE(D3D12_COMPARISON_FUNC_ALWAYS)
)

// ステンシル演算
FWK_JSON_SERIALIZE_ENUM(D3D12_STENCIL_OP,
	FWK_JSON_ENUM_VALUE(D3D12_STENCIL_OP_KEEP),
	FWK_JSON_ENUM_VALUE(D3D12_STENCIL_OP_ZERO),
	FWK_JSON_ENUM_VALUE(D3D12_STENCIL_OP_REPLACE),
	FWK_JSON_ENUM_VALUE(D3D12_STENCIL_OP_INCR_SAT),
	FWK_JSON_ENUM_VALUE(D3D12_STENCIL_OP_DECR_SAT),
	FWK_JSON_ENUM_VALUE(D3D12_STENCIL_OP_INVERT),
	FWK_JSON_ENUM_VALUE(D3D12_STENCIL_OP_INCR),
	FWK_JSON_ENUM_VALUE(D3D12_STENCIL_OP_DECR)
)

// DXGIフォーマット
FWK_JSON_SERIALIZE_ENUM(DXGI_FORMAT,
	FWK_JSON_ENUM_VALUE(DXGI_FORMAT_UNKNOWN),
	FWK_JSON_ENUM_VALUE(DXGI_FORMAT_R8G8B8A8_UNORM),
	FWK_JSON_ENUM_VALUE(DXGI_FORMAT_D24_UNORM_S8_UINT),
	FWK_JSON_ENUM_VALUE(DXGI_FORMAT_D32_FLOAT)
)

// プリミティブトポロジタイプ
FWK_JSON_SERIALIZE_ENUM(D3D12_PRIMITIVE_TOPOLOGY_TYPE,
	FWK_JSON_ENUM_VALUE(D3D12_PRIMITIVE_TOPOLOGY_TYPE_UNDEFINED),
	FWK_JSON_ENUM_VALUE(D3D12_PRIMITIVE_TOPOLOGY_TYPE_POINT),
	FWK_JSON_ENUM_VALUE(D3D12_PRIMITIVE_TOPOLOGY_TYPE_LINE),
	FWK_JSON_ENUM_VALUE(D3D12_PRIMITIVE_TOPOLOGY_TYPE_TRIANGLE),
	FWK_JSON_ENUM_VALUE(D3D12_PRIMITIVE_TOPOLOGY_TYPE_PATCH)
)

// ディスクリプタレンジタイプ
FWK_JSON_SERIALIZE_ENUM(D3D12_DESCRIPTOR_RANGE_TYPE,
	FWK_JSON_ENUM_VALUE(D3D12_DESCRIPTOR_RANGE_TYPE_SRV),
	FWK_JSON_ENUM_VALUE(D3D12_DESCRIPTOR_RANGE_TYPE_UAV),
	FWK_JSON_ENUM_VALUE(D3D12_DESCRIPTOR_RANGE_TYPE_CBV),
	FWK_JSON_ENUM_VALUE(D3D12_DESCRIPTOR_RANGE_TYPE_SAMPLER)
)

// ルートパラメータタイプ
FWK_JSON_SERIALIZE_ENUM(D3D12_ROOT_PARAMETER_TYPE,
	FWK_JSON_ENUM_VALUE(D3D12_ROOT_PARAMETER_TYPE_DESCRIPTOR_TABLE),
	FWK_JSON_ENUM_VALUE(D3D12_ROOT_PARAMETER_TYPE_32BIT_CONSTANTS),
	FWK_JSON_ENUM_VALUE(D3D12_ROOT_PARAMETER_TYPE_CBV),
	FWK_JSON_ENUM_VALUE(D3D12_ROOT_PARAMETER_TYPE_SRV),
	FWK_JSON_ENUM_VALUE(D3D12_ROOT_PARAMETER_TYPE_UAV)
)

// シェーダー可視性
FWK_JSON_SERIALIZE_ENUM(D3D12_SHADER_VISIBILITY,
	FWK_JSON_ENUM_VALUE(D3D12_SHADER_VISIBILITY_ALL),
	FWK_JSON_ENUM_VALUE(D3D12_SHADER_VISIBILITY_VERTEX),
	FWK_JSON_ENUM_VALUE(D3D12_SHADER_VISIBILITY_HULL),
	FWK_JSON_ENUM_VALUE(D3D12_SHADER_VISIBILITY_DOMAIN),
	FWK_JSON_ENUM_VALUE(D3D12_SHADER_VISIBILITY_GEOMETRY),
	FWK_JSON_ENUM_VALUE(D3D12_SHADER_VISIBILITY_PIXEL),
	FWK_JSON_ENUM_VALUE(D3D12_SHADER_VISIBILITY_AMPLIFICATION),
	FWK_JSON_ENUM_VALUE(D3D12_SHADER_VISIBILITY_MESH)
)

// フィルターモード
FWK_JSON_SERIALIZE_ENUM(D3D12_FILTER,
	FWK_JSON_ENUM_VALUE(D3D12_FILTER_MIN_MAG_MIP_POINT),
	FWK_JSON_ENUM_VALUE(D3D12_FILTER_MIN_MAG_MIP_LINEAR)
)

// テクスチャアドレスモード
FWK_JSON_SERIALIZE_ENUM(D3D12_TEXTURE_ADDRESS_MODE,
	FWK_JSON_ENUM_VALUE(D3D12_TEXTURE_ADDRESS_MODE_WRAP),
	FWK_JSON_ENUM_VALUE(D3D12_TEXTURE_ADDRESS_MODE_MIRROR),
	FWK_JSON_ENUM_VALUE(D3D12_TEXTURE_ADDRESS_MODE_CLAMP),
	FWK_JSON_ENUM_VALUE(D3D12_TEXTURE_ADDRESS_MODE_BORDER)
)

// スタティックサンプラー境界色
FWK_JSON_SERIALIZE_ENUM(D3D12_STATIC_BORDER_COLOR,
	FWK_JSON_ENUM_VALUE(D3D12_STATIC_BORDER_COLOR_TRANSPARENT_BLACK),
	FWK_JSON_ENUM_VALUE(D3D12_STATIC_BORDER_COLOR_OPAQUE_BLACK),
	FWK_JSON_ENUM_VALUE(D3D12_STATIC_BORDER_COLOR_OPAQUE_WHITE)
)

// ルートシグネチャフラグ
FWK_JSON_SERIALIZE_ENUM(D3D12_ROOT_SIGNATURE_FLAGS,
	FWK_JSON_ENUM_VALUE(D3D12_ROOT_SIGNATURE_FLAG_NONE),
	FWK_JSON_ENUM_VALUE(D3D12_ROOT_SIGNATURE_FLAG_ALLOW_INPUT_ASSEMBLER_INPUT_LAYOUT)
)

// ルートシグネチャバージョン
FWK_JSON_SERIALIZE_ENUM(D3D_ROOT_SIGNATURE_VERSION,
	FWK_JSON_ENUM_VALUE(D3D_ROOT_SIGNATURE_VERSION_1),
	FWK_JSON_ENUM_VALUE(D3D_ROOT_SIGNATURE_VERSION_1_0),
	FWK_JSON_ENUM_VALUE(D3D_ROOT_SIGNATURE_VERSION_1_1),
	FWK_JSON_ENUM_VALUE(D3D_ROOT_SIGNATURE_VERSION_1_2)
)

// ConservativeRasterizationモード
FWK_JSON_SERIALIZE_ENUM(D3D12_CONSERVATIVE_RASTERIZATION_MODE,
	FWK_JSON_ENUM_VALUE(D3D12_CONSERVATIVE_RASTERIZATION_MODE_OFF),
	FWK_JSON_ENUM_VALUE(D3D12_CONSERVATIVE_RASTERIZATION_MODE_ON)
)

// カラー書き込みマスク
FWK_JSON_SERIALIZE_ENUM(D3D12_COLOR_WRITE_ENABLE,
	FWK_JSON_ENUM_VALUE(D3D12_COLOR_WRITE_ENABLE_RED),
	FWK_JSON_ENUM_VALUE(D3D12_COLOR_WRITE_ENABLE_GREEN),
	FWK_JSON_ENUM_VALUE(D3D12_COLOR_WRITE_ENABLE_BLUE),
	FWK_JSON_ENUM_VALUE(D3D12_COLOR_WRITE_ENABLE_ALPHA),
	FWK_JSON_ENUM_VALUE(D3D12_COLOR_WRITE_ENABLE_ALL)
)

// 論理演算
FWK_JSON_SERIALIZE_ENUM(D3D12_LOGIC_OP,
	FWK_JSON_ENUM_VALUE(D3D12_LOGIC_OP_CLEAR),
	FWK_JSON_ENUM_VALUE(D3D12_LOGIC_OP_SET),
	FWK_JSON_ENUM_VALUE(D3D12_LOGIC_OP_COPY),
	FWK_JSON_ENUM_VALUE(D3D12_LOGIC_OP_COPY_INVERTED),
	FWK_JSON_ENUM_VALUE(D3D12_LOGIC_OP_NOOP),
	FWK_JSON_ENUM_VALUE(D3D12_LOGIC_OP_INVERT),
	FWK_JSON_ENUM_VALUE(D3D12_LOGIC_OP_AND),
	FWK_JSON_ENUM_VALUE(D3D12_LOGIC_OP_NAND),
	FWK_JSON_ENUM_VALUE(D3D12_LOGIC_OP_OR),
	FWK_JSON_ENUM_VALUE(D3D12_LOGIC_OP_NOR),
	FWK_JSON_ENUM_VALUE(D3D12_LOGIC_OP_XOR),
	FWK_JSON_ENUM_VALUE(D3D12_LOGIC_OP_EQUIV),
	FWK_JSON_ENUM_VALUE(D3D12_LOGIC_OP_AND_INVERTED),
	FWK_JSON_ENUM_VALUE(D3D12_LOGIC_OP_AND_REVERSE),
	FWK_JSON_ENUM_VALUE(D3D12_LOGIC_OP_OR_INVERTED)
);

// このヘッダ内のみで使用する補助マクロなので、定義使用後に#undefしておく
#undef FWK_JSON_ENUM_VALUE
#undef FWK_JSON_SERIALIZE_ENUM